# Generated by Django 5.1.2 on 2024-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_category_alter_product_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suppliers',
            new_name='suppliers_id',
        ),
    ]
