# Generated by Django 5.1.2 on 2024-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_category_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suppliers_id',
            new_name='suppliers',
        ),
    ]
